export const options = [
  { value: 'covid', label: 'covid' },
  { value: 'governo', label: 'governo' },
  { value: '2022', label: '2022' },
  { value: 'guerra', label: 'guerra' },
  { value: 'mundo', label: 'mundo' },
  { value: 'pop', label: 'pop' },
  { value: 'bts', label: 'bts' },
  { value: 'muzambinho', label: 'muzambinho' },
  { value: 'minas gerais', label: 'minas gerais' },
  { value: 'brasil', label: 'brasil' },
  { value: 'copa do mundo', label: 'copa do mundo' },
  { value: 'saude', label: 'saude' },
  { value: 'esporte', label: 'esporte' },
  { value: 'lazer', label: 'lazer' },
  { value: 'jogos', label: 'jogos' },
  { value: 'animes', label: 'animes' },
  { value: 'filmes', label: 'filmes' },
  { value: 'series', label: 'series' },
  { value: 'livros', label: 'livros' },
  { value: 'acidente', label: 'acidente' },
  { value: 'policia', label: 'policia' },
  { value: 'assalto', label: 'assalto' },
  { value: 'politica', label: 'politica' },
  { value: 'eleição', label: 'eleição' },
  { value: 'economia', label: 'economia' },
  { value: 'finança', label: 'finança' },
  { value: 'zona rural', label: 'zona rural' },
  { value: 'projeto', label: 'projeto' },
  { value: 'televisão', label: 'televisão' },
  { value: 'musica', label: 'musica' },
  { value: 'estrada', label: 'estrada' },
  { value: 'protesto', label: 'protesto' },
  { value: 'ATO', label: 'ATO' },
  { value: 'povo', label: 'povo' },
  { value: 'LOTERICA SUA CASA', label: 'LOTERICA SUA CASA' },
  { value: 'LOTERICA', label: 'LOTERICA' },
  { value: 'APOSTAS', label: 'APOSTAS' },
  { value: 'MEGA SENA', label: 'MEGA SENA' },
  { value: 'LOTO FACIL', label: 'LOTO FACIL' },
  { value: 'DUPLA SENA', label: 'DUPLA SENA' },
  { value: 'QUINA', label: 'QUINA' },
];
